---
- name: ensure cronjob is present
  hosts: all
  tasks:
    - name: ensure cronjob is present
      cron:
        name: "change led color"
        state: present
        user: pi
        job: "arr[0]="red";arr[1]="blue";arr[2]="green";rand=$[ $RANDOM % 3 ];/usr/bin/rgb ${arr[$rand]}"
