---
- name: webserver
  hosts: all
  gather_facts: false
  tasks:
    - name: install webserver
      become: yes
      apt:
        update_cache: yes
        name: apache2
        state: latest
    - name: apache2 autostart
      become: yes
      service:
        name: apache2
        state: started
        enabled: yes